# Generated by Django 6.0.4 on 2026-05-19 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_material_codigo_remove_material_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='codigo',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='stock_minimo',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='material',
            name='unidad_medida',
            field=models.CharField(max_length=50),
        ),
    ]
