# Generated by Django 6.0.4 on 2026-06-01 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_partidapresupuestaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partidapresupuestaria',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='partidapresupuestaria',
            name='fecha_registro',
        ),
        migrations.AddField(
            model_name='material',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.partidapresupuestaria'),
        ),
    ]
