# Generated by Django 6.0.4 on 2026-06-01 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_unidadmedida'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='unidad_medida_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.unidadmedida'),
        ),
    ]
