# Generated by Django 6.0.4 on 2026-06-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_material_unidad_medida_fk'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('partida', 'nombre'), name='material_unico_por_partida'),
        ),
    ]
