# Generated by Django 6.0.4 on 2026-06-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_material_material_unico_por_partida'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='stock_anterior',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='stock_resultante',
            field=models.IntegerField(default=0),
        ),
    ]
