# Generated by Django 6.0.4 on 2026-07-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_movimientoinventario_stock_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
