# Generated by Django 6.0.4 on 2026-07-07 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_movimientoinventario_costo_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(help_text='NIT o documento de identificación', max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='NotaIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_nota', models.CharField(help_text='Número correlativo de nota de ingreso', max_length=50, unique=True)),
                ('c31', models.CharField(blank=True, help_text='Documento de gasto SIGEP C-31', max_length=50, null=True)),
                ('nota_entrega', models.CharField(blank=True, help_text='Número de Nota de Entrega o Remisión', max_length=50, null=True)),
                ('factura', models.CharField(blank=True, help_text='Número de Factura de Compra', max_length=50, null=True)),
                ('reingreso', models.BooleanField(default=False, help_text='Indica si la entrada es por devolución/reingreso de oficina')),
                ('fecha', models.DateField(help_text='Fecha de recepción física de los bienes')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(help_text='Almacenero que registra el ingreso', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_ingreso', to='inventario.proveedor')),
            ],
            options={
                'verbose_name': 'Nota de Ingreso',
                'verbose_name_plural': 'Notas de Ingreso',
            },
        ),
        migrations.CreateModel(
            name='NotaIngresoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.material')),
                ('nota_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.notaingreso')),
            ],
        ),
    ]
