# Generated by Django 6.0.4 on 2026-07-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_proveedor_notaingreso_notaingresodetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='saldo_disponible_lote',
            field=models.IntegerField(default=0, help_text='Solo para ENTRADAS: Cantidad remanente de este lote para el costeo PEPS'),
        ),
    ]
