# Generated by Django 6.0.4 on 2026-07-14 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_movimientoinventario_saldo_disponible_lote'),
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='unidad_destino',
            field=models.ForeignKey(blank=True, help_text='Unidad organizacional de la Gobernación que consumió el material', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos', to='organizacion.unidadorganizacional'),
        ),
    ]
