# Generated by Django 6.0.4 on 2026-08-17 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('inventario', '0013_movimientoinventario_unidad_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaingreso',
            name='compra_menor_origen',
            field=models.ForeignKey(blank=True, help_text='Orden de Compra origen emitida por Bienes y Servicios', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_ingreso_asociadas', to='compras.compramenor'),
        ),
    ]
