# Generated by Django 6.0.4 on 2026-09-04 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_notaingreso_compra_menor_origen'),
        ('organizacion', '0003_secretaria_is_active_unidadorganizacional_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('CENTRAL', 'Almacén Central'), ('SUBALMACEN', 'Subalmacén / Seccional')], default='SUBALMACEN', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almacenes_bajo_responsabilidad', to=settings.AUTH_USER_MODEL)),
                ('unidad_organizacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almacenes', to='organizacion.unidadorganizacional')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.CreateModel(
            name='InventarioAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_disponible', models.IntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='inventario.almacen')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios_almacen', to='inventario.material')),
            ],
            options={
                'verbose_name': 'Inventario por Almacén',
                'verbose_name_plural': 'Inventarios por Almacén',
                'unique_together': {('material', 'almacen')},
            },
        ),
    ]
