# Generated by Django 6.0.4 on 2026-09-04 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_almacen_inventarioalmacen'),
        ('organizacion', '0003_secretaria_is_active_unidadorganizacional_is_active'),
        ('solicitudes', '0015_detallesolicitud_partida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_nota', models.CharField(help_text='Número correlativo de la nota de salida o acta de entrega', max_length=50, unique=True)),
                ('fecha', models.DateField(help_text='Fecha de egreso físico y firma de entrega')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('solicitud_origen', models.ForeignKey(help_text='Solicitud autorizada que originó el egreso físico', on_delete=django.db.models.deletion.PROTECT, related_name='notas_salida', to='solicitudes.solicitud')),
                ('unidad_destino', models.ForeignKey(help_text='Unidad organizacional de la Gobernación que recibe el material', on_delete=django.db.models.deletion.PROTECT, related_name='notas_salida', to='organizacion.unidadorganizacional')),
                ('usuario', models.ForeignKey(help_text='Almacenero que procesa el despacho', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de Salida',
                'verbose_name_plural': 'Notas de Salida',
            },
        ),
        migrations.CreateModel(
            name='NotaSalidaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('costo_unitario_real', models.DecimalField(decimal_places=2, help_text='Costo real de salida determinado por el lote PEPS', max_digits=12)),
                ('costo_total_real', models.DecimalField(decimal_places=2, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.material')),
                ('nota_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.notasalida')),
            ],
            options={
                'verbose_name': 'Detalle de Nota de Salida',
                'verbose_name_plural': 'Detalles de Nota de Salida',
            },
        ),
    ]
