# Generated by Django 6.0.4 on 2026-09-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_notasalida_notasalidadetalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventarioalmacen',
            old_name='stock_disponible',
            new_name='stock_fisico',
        ),
        migrations.AddField(
            model_name='inventarioalmacen',
            name='stock_reservado',
            field=models.IntegerField(default=0),
        ),
    ]
