# Generated by Django 6.0.4 on 2026-09-06 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_rename_stock_disponible_inventarioalmacen_stock_fisico_and_more'),
        ('organizacion', '0003_secretaria_is_active_unidadorganizacional_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notaingresodetalle',
            options={'verbose_name': 'Detalle de Nota de Ingreso', 'verbose_name_plural': 'Detalles de Nota de Ingreso'},
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='almacen',
            field=models.ForeignKey(blank=True, help_text='Almacén o subalmacén donde ocurre físicamente el movimiento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.almacen'),
        ),
        migrations.AddField(
            model_name='notaingreso',
            name='almacen_destino',
            field=models.ForeignKey(blank=True, help_text='Almacén o subalmacén donde ingresarán físicamente los bienes', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_ingreso', to='inventario.almacen'),
        ),
        migrations.AddField(
            model_name='notasalida',
            name='almacen_origen',
            field=models.ForeignKey(blank=True, help_text='Almacén o subalmacén de donde se despacha el stock', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_salida', to='inventario.almacen'),
        ),
        migrations.AlterField(
            model_name='notasalida',
            name='unidad_destino',
            field=models.ForeignKey(help_text='Unidad de la Gobernación que recibe el material', on_delete=django.db.models.deletion.PROTECT, related_name='notas_salida', to='organizacion.unidadorganizacional'),
        ),
        migrations.AlterField(
            model_name='partidapresupuestaria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
