# Generated by Django 6.0.4 on 2026-09-07 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_material_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_transferencia', models.CharField(help_text='Número correlativo oficial de transferencia (ej: TR-00001)', max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('EN_TRANSITO', 'En Tránsito / Enviado'), ('RECIBIDA', 'Recibida / Consolidada'), ('RECHAZADA', 'Rechazada / Devuelta')], default='EN_TRANSITO', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('destino', models.ForeignKey(help_text='Almacén receptor', on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recibidas', to='inventario.almacen')),
                ('origen', models.ForeignKey(help_text='Almacén despachador', on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to='inventario.almacen')),
                ('usuario_envia', models.ForeignKey(help_text='Almacenero que despacha del origen', on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_despachadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_recibe', models.ForeignKey(blank=True, help_text='Almacenero que acepta en el destino', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recepcionadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia entre Almacenes',
                'verbose_name_plural': 'Transferencias entre Almacenes',
            },
        ),
        migrations.CreateModel(
            name='TransferenciaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('costo_unitario_transferencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('costo_total_transferencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.material')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.transferencia')),
            ],
        ),
    ]
