# Generated by Django 6.0.4 on 2026-09-10 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_transferencia_transferenciadetalle'),
        ('organizacion', '0003_secretaria_is_active_unidadorganizacional_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='almacen_padre',
            field=models.ForeignKey(blank=True, help_text='Si está en blanco, es almacén principal. Si tiene valor, depende de ese almacén.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subalmacenes', to='inventario.almacen'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='unidades_atendidas',
            field=models.ManyToManyField(blank=True, help_text='Unidades a las que este almacén está autorizado a despachar materiales.', related_name='almacenes_que_atienden', to='organizacion.unidadorganizacional'),
        ),
    ]
