# Generated by Django 6.0.4 on 2026-09-17 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_almacen_almacen_padre_almacen_unidades_atendidas'),
        ('organizacion', '0003_secretaria_is_active_unidadorganizacional_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionMaterialUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.IntegerField(default=2026, help_text='Gestión fiscal de la asignación')),
                ('cantidad_asignada', models.IntegerField(default=0, help_text='Cupo físico máximo autorizado para la gestión')),
                ('cantidad_consumida', models.IntegerField(default=0, help_text='Cantidad física retirada formalmente hasta la fecha')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_unidades', to='inventario.material')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_materiales', to='organizacion.unidadorganizacional')),
            ],
            options={
                'verbose_name': 'Asignación de Material por Unidad',
                'verbose_name_plural': 'Asignaciones de Material por Unidad',
                'unique_together': {('unidad', 'material', 'gestion')},
            },
        ),
    ]
