# Generated by Django 6.0.4 on 2026-09-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_asignacionmaterialunidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de caducidad/vencimiento para insumos perecederos (químicos, tintas, reactivos, etc.)', null=True),
        ),
    ]
