# Generated by Django 6.0.4 on 2026-09-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_movimientoinventario_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='material',
            name='material_unico_por_partida',
        ),
        migrations.AddField(
            model_name='material',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento opcional para productos perecederos (químicos, tintas, limpieza, etc.)', null=True),
        ),
    ]
