# Generated by Django 6.0.4 on 2026-09-25 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_remove_material_material_unico_por_partida_and_more'),
        ('organizacion', '0003_secretaria_is_active_unidadorganizacional_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='fecha_vencimiento',
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.almacen'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento del lote recibido', null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='saldo_disponible_lote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='unidad_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos', to='organizacion.unidadorganizacional'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('partida', 'nombre'), name='material_unico_por_partida'),
        ),
    ]
