# Generated by Django 6.0.4 on 2026-09-28 05:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0025_remove_material_fecha_vencimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteCierreAuditado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_documento', models.CharField(help_text='Ej: CIERRE-2025-R105-001', max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('DGCF_R105', 'Resumen de Almacenes por Partida (DGCF - R1.05)'), ('DGCF_R106', 'Detalle Físico-Valorado por Ítem (DGCF - R1.06)'), ('CIERRE_ANUAL', 'Acta de Cierre de Gestión Anual')], max_length=20)),
                ('gestion', models.IntegerField(default=2026)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total_items', models.IntegerField(default=0)),
                ('valor_total_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes_cierres/%Y/')),
                ('hash_seguridad', models.CharField(blank=True, help_text='Firma SHA-256 del archivo', max_length=64, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Cierre Auditado',
                'verbose_name_plural': 'Reportes de Cierre Auditados',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
