# Generated by Django 6.0.4 on 2026-10-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_reportecierreauditado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'ordering': ['codigo'], 'verbose_name': 'Unidad de Medida', 'verbose_name_plural': 'Unidades de Medida'},
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Baja lógica de la unidad de medida'),
        ),
    ]
