# Generated by Django 6.0.4 on 2026-10-05 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_alter_unidadmedida_options_unidadmedida_is_active'),
        ('organizacion', '0003_secretaria_is_active_unidadorganizacional_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionEntradaUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_asignada', models.IntegerField(help_text='Cupo físico total asignado a esta oficina en esta compra')),
                ('cantidad_retirada', models.IntegerField(default=0, help_text='Cantidad física ya despachada mediante Solicitudes autorizadas')),
                ('nota_ingreso_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_unidades', to='inventario.notaingresodetalle')),
                ('unidad_organizacional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_compras', to='organizacion.unidadorganizacional')),
            ],
            options={
                'verbose_name': 'Asignación de Entrada a Unidad',
                'verbose_name_plural': 'Asignaciones de Entrada a Unidades',
                'unique_together': {('nota_ingreso_detalle', 'unidad_organizacional')},
            },
        ),
    ]
