# Generated by Django 6.0.4 on 2026-10-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0028_asignacionentradaunidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaingreso',
            name='nro_orden_compra',
            field=models.CharField(blank=True, help_text='Ej: COMPRA 168/2026 o BB.SS. N° 081/2026', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notaingreso',
            name='observaciones',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
