# Generated by Django 6.0.4 on 2026-06-19 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0009_movimientoinventario_stock_anterior_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.IntegerField()),
                ('monto_asignado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_ejecutado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.partidapresupuestaria')),
            ],
        ),
    ]
