# Generated by Django 6.0.4 on 2026-07-14 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0013_movimientoinventario_unidad_destino'),
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.IntegerField(default=2026, help_text='Año de gestión fiscal de la Gobernación')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0.0, help_text='Presupuesto de apertura asignado', max_digits=12)),
                ('monto_disponible', models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo presupuestario remanente', max_digits=12)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poas', to='inventario.partidapresupuestaria')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='poas', to='organizacion.unidadorganizacional')),
            ],
            options={
                'verbose_name': 'POA',
                'verbose_name_plural': 'POAs',
                'unique_together': {('unidad', 'partida', 'gestion')},
            },
        ),
    ]
