# Generated by Django 6.0.4 on 2026-09-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poa',
            name='monto_comprometido',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Presupuesto reservado provisionalmente para adquisiciones aprobadas', max_digits=12),
        ),
        migrations.AddField(
            model_name='poa',
            name='monto_ejecutado',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Presupuesto gastado de forma definitiva', max_digits=12),
        ),
    ]
