# Generated by Django 6.0.4 on 2026-09-02 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0002_poa_monto_comprometido_poa_monto_ejecutado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='poa',
            name='monto_ejecutado',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Presupuesto gastado de forma definitiva tras la entrega/compra real', max_digits=12),
        ),
        migrations.CreateModel(
            name='ModificacionPresupuestaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INCREMENTO', 'Incremento Presupuestario'), ('REDUCCION', 'Reducción Presupuestaria')], help_text='Tipo de ajuste presupuestario', max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del ajuste en bolivianos', max_digits=12)),
                ('justificacion', models.TextField(help_text='Justificación técnica o resolución administrativa del traspaso')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('poa', models.ForeignKey(help_text='POA al que se le aplicará el ajuste', on_delete=django.db.models.deletion.CASCADE, related_name='modificaciones', to='presupuestos.poa')),
                ('usuario', models.ForeignKey(help_text='Analista de presupuestos que registra la modificación', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modificación Presupuestaria',
                'verbose_name_plural': 'Modificaciones Presupuestarias',
            },
        ),
    ]
