# Generated by Django 6.0.4 on 2026-09-18 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_asignacionmaterialunidad'),
        ('presupuestos', '0003_alter_poa_monto_ejecutado_modificacionpresupuestaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProgramacionPOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_actividad_poa', models.CharField(default='13.1 - 13.4', help_text='Código de operación/actividad en el POA (Columna 1 Form. 005)', max_length=50)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad_programada', models.IntegerField(help_text='Cantidad anual demandada en el Formulario 005')),
                ('cantidad_consumida', models.IntegerField(default=0, help_text='Cantidad física ya retirada mediante notas de salida')),
                ('precio_unitario_estimado', models.DecimalField(decimal_places=2, help_text='Precio referencial unitario presupuestado (Bs.)', max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Monto total presupuestado para este material (Cantidad x P. Unitario)', max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones_poa', to='inventario.material')),
                ('poa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programacion_items', to='presupuestos.poa')),
            ],
            options={
                'verbose_name': 'Detalle de Programación POA (Form. 005)',
                'verbose_name_plural': 'Detalles de Programación POA (Form. 005)',
            },
        ),
    ]
