# Generated by Django 6.0.4 on 2026-05-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('UNIDAD_SOLICITANTE', 'Unidad Solicitante'), ('JEFE_INMEDIATO', 'Jefe Inmediato Superior'), ('ALMACENERO', 'Almacenero'), ('KARDISTA', 'Kardista'), ('PRESUPUESTOS', 'Unidad de Presupuestos'), ('BIENES_SERVICIOS', 'Unidad de Bienes y Servicios'), ('PROVEEDOR', 'Proveedor'), ('ADMINISTRADOR', 'Administrador del Sistema')], default='SOLICITANTE', max_length=20),
        ),
    ]
