# Generated by Django 6.0.4 on 2026-07-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_perfilusuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('UNIDAD_SOLICITANTE', 'Unidad Solicitante'), ('JEFE_INMEDIATO', 'Jefe Inmediato Superior'), ('ALMACENERO', 'Almacenero'), ('KARDISTA', 'Kardista'), ('PRESUPUESTOS', 'Unidad de Presupuestos'), ('BIENES_SERVICIOS', 'Unidad de Bienes y Servicios'), ('ADMINISTRADOR', 'Administrador del Sistema')], default='UNIDAD_SOLICITANTE', max_length=20),
        ),
    ]
