# Generated by Django 6.0.4 on 2026-08-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_perfilusuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('UNIDAD_SOLICITANTE', 'Unidad Solicitante'), ('JEFE_INMEDIATO', 'Jefe Inmediato Superior'), ('ALMACENERO', 'Almacenero'), ('KARDISTA', 'Kardista'), ('PRESUPUESTOS', 'Unidad de Presupuestos'), ('BIENES_SERVICIOS', 'Unidad de Bienes y Servicios'), ('ADMINISTRADOR', 'Administrador del Sistema'), ('SECRETARIO_SAF', 'Secretario de la SAF'), ('RPA', 'Responsable del Proceso de Contratación (RPA)'), ('JEFE_ADMINISTRATIVO', 'Jefe Administrativo')], default='UNIDAD_SOLICITANTE', max_length=20),
        ),
    ]
