# Generated by Django 6.0.4 on 2026-08-28 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0002_secretaria_unidadadministrativa_and_more'),
        ('usuarios', '0006_alter_perfilusuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_usuarios', to='organizacion.secretaria'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles_usuarios', to='organizacion.unidadadministrativa'),
        ),
    ]
