# Generated by Django 6.0.4 on 2026-09-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_almacen_inventarioalmacen'),
        ('usuarios', '0007_perfilusuario_secretaria_alter_perfilusuario_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='almacenes_autorizados',
            field=models.ManyToManyField(blank=True, help_text='Almacenes autorizados que este usuario puede administrar u operar', related_name='usuarios_autorizados', to='inventario.almacen'),
        ),
    ]
