# Generated by Django 6.0.4 on 2026-09-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_almacen_almacen_padre_almacen_unidades_atendidas'),
        ('usuarios', '0008_perfilusuario_almacenes_autorizados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='almacenes_autorizados',
            field=models.ManyToManyField(blank=True, help_text='Almacenes en los que el usuario puede realizar operaciones.', related_name='usuarios_autorizados', to='inventario.almacen'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('UNIDAD_SOLICITANTE', 'Unidad Solicitante'), ('JEFE_INMEDIATO', 'Jefe Inmediato Superior'), ('ALMACENERO', 'Almacenero'), ('KARDISTA', 'Kardista'), ('ADMIN_ALMACENES', 'Administrador de Almacenes'), ('PRESUPUESTOS', 'Unidad de Presupuestos'), ('BIENES_SERVICIOS', 'Unidad de Bienes y Servicios'), ('ADMINISTRADOR', 'Administrador del Sistema'), ('SECRETARIO_SAF', 'Secretario de la SAF'), ('RPA', 'Responsable del Proceso de Contratación (RPA)'), ('JEFE_ADMINISTRATIVO', 'Jefe Administrativo')], default='UNIDAD_SOLICITANTE', max_length=30),
        ),
    ]
