# Generated by Django 6.0.4 on 2026-05-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_solicitud_unidad_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='unidad_solicitante',
            field=models.CharField(max_length=200),
        ),
    ]
