# Generated by Django 6.0.4 on 2026-05-20 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
        ('solicitudes', '0003_alter_solicitud_unidad_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='unidad_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacion.unidadorganizacional'),
        ),
    ]
