# Generated by Django 6.0.4 on 2026-05-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_alter_solicitud_unidad_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_JEFE', 'Pendiente Jefe'), ('VALIDADO', 'Validado'), ('RECHAZADO', 'Rechazado'), ('PENDIENTE_COMPRA', 'Pendiente Compra'), ('ENTREGADO', 'Entregado')], default='PENDIENTE_JEFE', max_length=20),
        ),
    ]
