# Generated by Django 6.0.4 on 2026-06-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_solicitud_motivo_rechazo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallesolicitud',
            old_name='cantidad',
            new_name='cantidad_solicitada',
        ),
        migrations.AddField(
            model_name='detallesolicitud',
            name='cantidad_aprobada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallesolicitud',
            name='cantidad_entregada',
            field=models.IntegerField(default=0),
        ),
    ]
