# Generated by Django 6.0.4 on 2026-07-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_rename_cantidad_detallesolicitud_cantidad_solicitada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('REGISTRADA', 'Registrada'), ('REVISADA', 'Revisada'), ('APROBADA', 'Aprobada'), ('PREPARADA', 'Preparada'), ('ENTREGADA', 'Entregada'), ('CERRADA', 'Cerrada'), ('RECHAZADA', 'Rechazada')], default='REGISTRADA', max_length=20),
        ),
    ]
