# Generated by Django 6.0.4 on 2026-07-28 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_movimientoinventario_unidad_destino'),
        ('solicitudes', '0008_alter_solicitud_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesolicitud',
            name='descripcion_material_no_catalogado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='detallesolicitud',
            name='es_nueva_adquisicion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detallesolicitud',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.material'),
        ),
    ]
