# Generated by Django 6.0.4 on 2026-08-05 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0010_solicitud_cerrado_por_solicitud_entregado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='fecha_revision',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='revisado_por',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_jefatura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_rpa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_saf',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='jefatura_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jefatura_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='rpa_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rpa_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='saf_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saf_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('REGISTRADA', 'Creada'), ('VALIDADA_SAF', 'Validada por SAF'), ('VALIDADA_PRESUPUESTOS', 'Validada por Presupuestos'), ('VALIDADA_RPA', 'Validada por RPA'), ('VALIDADA_JEFATURA', 'Validada por Jefatura Administrativa'), ('PREPARADA', 'Preparada'), ('ENTREGADA', 'Entregada'), ('CERRADA', 'Cerrada'), ('RECHAZADA', 'Rechazada')], default='REGISTRADA', max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='presupuestado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_validados', to=settings.AUTH_USER_MODEL),
        ),
    ]
