# Generated by Django 6.0.4 on 2026-09-02 04:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0012_solicitud_fecha_revision_solicitud_revisado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesolicitud',
            name='precio_unitario_referencial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo_requerimiento',
            field=models.CharField(choices=[('BIEN', 'Bien'), ('SERVICIO', 'Servicio')], default='BIEN', max_length=15),
        ),
    ]
