# Generated by Django 6.0.4 on 2026-09-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0013_detallesolicitud_precio_unitario_referencial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='flujo_atencion',
            field=models.CharField(blank=True, choices=[('SALIDA_ALMACEN', 'Salida de Almacén (Stock Disponible)'), ('ADQUISICION', 'Proceso de Adquisición (Sin Stock / Compra)'), ('CONTRATACION_SERVICIO', 'Contratación de Servicio')], max_length=30, null=True),
        ),
    ]
