# Generated by Django 6.0.4 on 2026-09-02 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_notaingreso_compra_menor_origen'),
        ('solicitudes', '0014_solicitud_flujo_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesolicitud',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_solicitud', to='inventario.partidapresupuestaria'),
        ),
    ]
