# Generated by Django 6.0.4 on 2026-09-21 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_almacen_almacen_padre_almacen_unidades_atendidas'),
        ('solicitudes', '0015_detallesolicitud_partida'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='almacen_operativo',
            field=models.ForeignKey(blank=True, help_text='Tarjeta 5: Almacén de despacho congelado al momento de la reserva (revisión).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_operativas', to='inventario.almacen'),
        ),
    ]
