# Generated by Django 6.0.4 on 2026-05-20 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadOrganizacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('SECRETARIA', 'Secretaría'), ('DIRECCION', 'Dirección'), ('JEFATURA', 'Jefatura'), ('AREA', 'Área')], max_length=20)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependencias', to='organizacion.unidadorganizacional')),
            ],
        ),
    ]
