# Generated by Django 6.0.4 on 2026-08-28 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadAdministrativa',
            fields=[
            ],
            options={
                'verbose_name': 'Unidad Administrativa',
                'verbose_name_plural': 'Unidades Administrativas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('organizacion.unidadorganizacional',),
        ),
        migrations.RemoveField(
            model_name='unidadorganizacional',
            name='padre',
        ),
        migrations.RemoveField(
            model_name='unidadorganizacional',
            name='tipo',
        ),
        migrations.AddField(
            model_name='unidadorganizacional',
            name='codigo_sigep',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unidadorganizacional',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades_organizacionales', to='organizacion.secretaria'),
        ),
    ]
