# Generated by Django 6.0.4 on 2026-08-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0002_secretaria_unidadadministrativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretaria',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unidadorganizacional',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
