# Generated by Django 6.0.4 on 2026-07-28 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0013_movimientoinventario_unidad_destino'),
        ('solicitudes', '0008_alter_solicitud_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraMenor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_orden', models.CharField(help_text='Número de Orden de Compra/Servicio', max_length=50, unique=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gestion', models.IntegerField(default=2026)),
                ('completada', models.BooleanField(default=False, help_text='Indica si los materiales ya fueron recepcionados en Almacén')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_menores', to='inventario.partidapresupuestaria')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_menores', to='inventario.proveedor')),
                ('solicitud_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_menores', to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name': 'Compra Menor',
                'verbose_name_plural': 'Compras Menores',
            },
        ),
        migrations.CreateModel(
            name='ActaConformidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_acta', models.CharField(max_length=50, unique=True)),
                ('fecha_firma', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('firmado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('compra_menor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acta_conformidad', to='compras.compramenor')),
            ],
            options={
                'verbose_name': 'Acta de Conformidad',
                'verbose_name_plural': 'Actas de Conformidad',
            },
        ),
    ]
