# Generated by Django 6.0.4 on 2026-09-23 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('inventario', '0022_asignacionmaterialunidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compramenor',
            options={'verbose_name': 'Orden de Compra / Servicio', 'verbose_name_plural': 'Órdenes de Compra y Servicio'},
        ),
        migrations.AddField(
            model_name='compramenor',
            name='estado',
            field=models.CharField(choices=[('EMITIDA', 'Emitida / Autorizada por RPA'), ('RECEPCIONADA', 'Recepcionada en Almacén (Solo Bienes)'), ('CONCLUIDA', 'Concluida / Conforme'), ('ANULADA', 'Anulada')], default='EMITIDA', max_length=20),
        ),
        migrations.AddField(
            model_name='compramenor',
            name='tipo_orden',
            field=models.CharField(choices=[('COMPRA', 'Orden de Compra (Bienes / Materiales)'), ('SERVICIO', 'Orden de Servicio (Servicios Generales)')], default='COMPRA', help_text='Define si ingresa físicamente a Almacén (Compra) o es prestación directa (Servicio)', max_length=20),
        ),
        migrations.AlterField(
            model_name='compramenor',
            name='nro_orden',
            field=models.CharField(help_text='Ej: BB.SS. N° 081/2026 o BB.SS. N° 026/2024', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='DetalleCompraMenor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('unidad_medida', models.CharField(default='Pza', max_length=50)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compramenor')),
                ('material', models.ForeignKey(blank=True, help_text='Material del catálogo si ya existía en almacenes', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.material')),
            ],
            options={
                'verbose_name': 'Detalle de Orden de Compra/Servicio',
                'verbose_name_plural': 'Detalles de Orden de Compra/Servicio',
            },
        ),
    ]
