# Generated by Django 6.0.4 on 2026-10-05 08:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_compramenor_options_compramenor_estado_and_more'),
        ('inventario', '0029_notaingreso_nro_orden_compra_and_more'),
        ('organizacion', '0003_secretaria_is_active_unidadorganizacional_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoridadInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('RPA', 'Responsable del Proceso de Contratación (RPA)'), ('SAF', 'Secretario(a) Dptal. Administrativo y Financiero'), ('MAE', 'Máxima Autoridad Ejecutiva (Gobernador)')], max_length=10)),
                ('nombre_completo', models.CharField(help_text='Ej: Lic. Flora Colque Calizaya', max_length=200)),
                ('resolucion_designacion', models.CharField(help_text='Ej: Resolución Administrativa N° 045/2026', max_length=150)),
                ('fecha_designacion', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Vigencia de designación', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Marca si esta autoridad está en funciones')),
            ],
            options={
                'verbose_name': 'Autoridad Institucional',
                'verbose_name_plural': 'Autoridades Institucionales',
            },
        ),
        migrations.CreateModel(
            name='RequisitoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('aplica_a', models.CharField(choices=[('BIEN', 'Solo Bienes'), ('SERVICIO', 'Solo Servicios'), ('AMBOS', 'Bienes y Servicios')], default='AMBOS', max_length=10)),
                ('es_obligatorio', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Requisito de Checklist',
                'verbose_name_plural': 'Requisitos de Checklist',
            },
        ),
        migrations.CreateModel(
            name='ProcesoAdquisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: ADQ-2026-0001', max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('BIEN', 'Bien (Adquisición Directa / Sin Stock)'), ('SERVICIO', 'Servicio (Contratación de Servicios)')], default='BIEN', max_length=15)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('objeto_contratacion', models.CharField(help_text='Objeto de la contratación', max_length=300)),
                ('justificacion', models.TextField()),
                ('cite_solicitud', models.CharField(blank=True, help_text='CITE inicial de la oficina', max_length=100, null=True)),
                ('cite_nota_saf', models.CharField(blank=True, help_text='CITE de nota a SAF', max_length=100, null=True)),
                ('cite_aprobacion_rpa', models.CharField(blank=True, help_text='CITE de nota/proveído RPA', max_length=100, null=True)),
                ('certificacion_nro', models.CharField(blank=True, help_text='N° de Certificación Presupuestaria', max_length=50, null=True)),
                ('fuente_financiamiento', models.CharField(blank=True, help_text='Ej: 20 - Recursos Específicos', max_length=100, null=True)),
                ('organismo_financiador', models.CharField(blank=True, help_text='Ej: 111 - Tesoro General', max_length=100, null=True)),
                ('monto_certificado_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('hecho_en_bolivia', models.CharField(choices=[('SI', 'Sí, existe producción nacional'), ('NO', 'No existe producción nacional'), ('NO_APLICA', 'No Aplica')], default='NO_APLICA', max_length=20)),
                ('documento_hecho_en_bolivia', models.CharField(blank=True, help_text='N° de verificación digital Promueve Bolivia', max_length=150, null=True)),
                ('nro_orden_compra', models.CharField(blank=True, help_text='N° Orden de Compra o Servicio oficial', max_length=100, null=True)),
                ('precio_oficial_adjudicado_bs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('recepcion_conforme', models.BooleanField(default=False)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('nro_nota_recepcion', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones_recepcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('INICIADA', '1. Registrada'), ('CHECKLIST_VERIFICADO', '2. Checklist Aprobado'), ('NOTA_SAF_EMITIDA', '3. Nota Enviada a SAF'), ('CERTIFICADA', '4. Presupuesto Certificado'), ('APROBADA_RPA', '5. Aprobado por RPA'), ('ORDEN_EMITIDA', '6. Orden Emitida (Precio Oficial)'), ('RECEPCIONADA', '7. Recepcionado en Almacén (Documental)'), ('CONCLUIDA', '8. Trámite Concluido'), ('ANULADA', 'Anulada')], default='INICIADA', max_length=25)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('autoridad_rpa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adquisiciones_rpa', to='compras.autoridadinstitucional')),
                ('autoridad_saf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adquisiciones_saf', to='compras.autoridadinstitucional')),
                ('partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.partidapresupuestaria')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adquisiciones_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('unidad_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizacion.unidadorganizacional')),
            ],
            options={
                'verbose_name': 'Proceso de Adquisición (Flujo 2)',
                'verbose_name_plural': 'Procesos de Adquisición (Flujo 2)',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoItemDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Especificaciones técnicas o Términos de Referencia')),
                ('unidad_medida', models.CharField(default='PIEZA', max_length=50)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_referencial_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('precio_oficial_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('material', models.ForeignKey(blank=True, help_text='Opcional si existe en catálogo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.material')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.procesoadquisicion')),
            ],
        ),
        migrations.CreateModel(
            name='ProcesoChecklistDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('CUMPLE', 'Cumple'), ('NO_CUMPLE', 'No Cumple / Pendiente'), ('NO_APLICA', 'No Aplica')], default='NO_CUMPLE', max_length=15)),
                ('documento_respaldo', models.CharField(blank=True, help_text='N° CITE / Folio de respaldo', max_length=200, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=300, null=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_respuestas', to='compras.procesoadquisicion')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.requisitocatalogo')),
            ],
        ),
    ]
