# Generated by Django 6.0.4 on 2026-10-06 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_autoridadinstitucional_requisitocatalogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesochecklistdetalle',
            name='item_adquisicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_respuestas', to='compras.procesoitemdetalle'),
        ),
    ]
