# Generated by Django 6.0.4 on 2026-10-07 20:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_procesochecklistdetalle_item_adquisicion'),
        ('inventario', '0029_notaingreso_nro_orden_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoitemdetalle',
            name='fuente_financiamiento',
            field=models.CharField(default='20 - Recursos Específicos', max_length=100),
        ),
        migrations.AddField(
            model_name='procesoitemdetalle',
            name='monto_certificado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='procesoitemdetalle',
            name='organismo_financiador',
            field=models.CharField(default='111 - TGN', max_length=100),
        ),
        migrations.AddField(
            model_name='procesoitemdetalle',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.partidapresupuestaria'),
        ),
    ]
