# Generated by Django 6.0.4 on 2026-10-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_procesoitemdetalle_fuente_financiamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoadquisicion',
            name='programa',
            field=models.CharField(default='000', help_text='Ej: 000', max_length=20),
        ),
        migrations.AddField(
            model_name='procesoadquisicion',
            name='proyecto_actividad',
            field=models.CharField(default='001', help_text='Ej: 001 o código de proyecto', max_length=20),
        ),
    ]
